{{--
    Shared RTL layout for row-per-record reports (leaves, requests).
    Expects $view: App\Modules\Reports\Exports\TabularPdfView.
    Same font strategy as attendance-monthly: Amiri when the host has
    internet egress, DejaVu Sans (bundled, covers Arabic) otherwise.
--}}
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <title>{{ $view->title() }}</title>
    <style>
        @if (app()->environment() !== 'testing')
        {{-- Skipped under tests: CI has no egress to fonts.gstatic.com. --}}
        @font-face {
            font-family: 'Amiri';
            font-style: normal;
            font-weight: 400;
            src: url('https://fonts.gstatic.com/s/amiri/v27/J7aRnpd8CGxBHqUpvrIw74NL.ttf') format('truetype');
        }
        @endif

        body { font-family: 'Amiri', 'DejaVu Sans', sans-serif; font-size: 9px; color: #1a1a1a; direction: rtl; margin: 0; }
        .page { padding: 20px 16px; }
        header.rpt-head { border-bottom: 3px solid #2678C4; padding-bottom: 10px; margin-bottom: 14px; }
        header.rpt-head h1 { margin: 0; font-size: 17px; color: #2678C4; }
        header.rpt-head .subtitle { margin: 2px 0 0; font-size: 11px; color: #4a4a4a; }
        table.rpt { width: 100%; border-collapse: collapse; direction: rtl; }
        table.rpt thead th { background: #2678C4; color: #ffffff; font-weight: bold; padding: 6px 4px; border: 1px solid #1f5f9d; text-align: center; }
        table.rpt tbody td { padding: 5px 4px; border: 1px solid #dcdcdc; vertical-align: middle; text-align: center; }
        table.rpt tbody tr:nth-child(even) td { background: #f6faff; }
        footer.rpt-foot { margin-top: 12px; padding-top: 6px; border-top: 1px solid #dcdcdc; font-size: 9px; color: #6a6a6a; text-align: left; direction: ltr; }
    </style>
</head>
<body>
<div class="page">
    <header class="rpt-head">
        <h1>{{ $view->title() }}</h1>
        <p class="subtitle">عدد السجلات: {{ $view->rows->count() }}</p>
    </header>

    <table class="rpt">
        <thead>
            <tr>
                @foreach ($view->headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($view->rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell ?? '—' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($view->headings) }}" style="padding:24px;color:#6a6a6a;">لا توجد بيانات مطابقة.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <footer class="rpt-foot">Generated by TAQAT &middot; {{ $view->generatedAt }}</footer>
</div>
</body>
</html>
