CREATE DATABASE IF NOT EXISTS taqat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'taqat'@'%' IDENTIFIED BY 'taqat_secret';
GRANT ALL PRIVILEGES ON taqat.* TO 'taqat'@'%';
FLUSH PRIVILEGES;
